version: "3.5"
services:
  app:
    container_name: app
    image: golang:1.14
    command: go run app/main.go
    environment:
      - APP_PORT=8000
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - lightnet
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"

  proxy:
    container_name: proxy
    image: golang:1.14
    command: go run proxy/main.go
    environment:
      - PROXY_PORT=3000
      - PROXY_UPSTREAM=http://app:8000
    ports:
      - 3000:3000
    depends_on:
      - app
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - lightnet
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"

networks:
  lightnet:
    name: lightnet_test_local
    driver: bridge
